title: Rebecca Muraya
email: rlmuraya@gmail.com
url: "https://rlmuraya.github.io"

exclude: ["README.rst"]
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default
      meta_description: |
        Python developer based in Raleigh/Durham, North Carolina.
sass:
    style: :compressed
